export default function MdxLayout({ children }: { children: React.ReactNode }) {
  return (
    <div
      className="
        prose
        max-w-none
        prose-headings:mt-8
        prose-headings:font-semibold
        prose-headings:text-black
        prose-h1:text-5xl
        prose-h2:text-4xl
        prose-h3:text-3xl
        prose-h4:text-2xl
        prose-h5:text-xl
        prose-h6:text-lg
        prose-p:leading-relaxed
        prose-p:text-zinc-800
        prose-blockquote:border-l-4
        prose-blockquote:border-l-zinc-300
        prose-blockquote/quote:text-zinc-500
        prose-code:bg-zinc-100
        prose-code:px-1.5
        prose-code:py-0.5
        prose-code:rounded
        prose-pre:bg-zinc-900
        prose-pre:text-white
        prose-pre:rounded-lg
        prose-pre:p-4
        prose-ul:list-disc
        prose-ol:list-decimal
        prose-li:my-1
        prose-a:text-blue-600
        prose-a:underline
        prose-img:rounded-lg
        prose-img:shadow-md
        dark:prose-headings:text-white
        dark:prose-p:text-zinc-300
        dark:prose-blockquote:border-l-zinc-700
        dark:prose-blockquote/quote:text-zinc-400
        dark:prose-pre:bg-zinc-900
        dark:prose-a:text-blue-400
        dark:prose-li:text-zinc-300
        wrap-break-word
        w-full
      "
    >
      {children}
    </div>
  )
}