import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css"
import Navbar from "@/components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased
        relative bg-zinc-900 overflow-x-hidden`}
      >
        <div className="hidden md:flex md:w-3/12
              fixed left-0 top-0 h-screen">
                <Navbar />
              </div>
              <div className="w-full md:w-9/12 md:ml-auto md:px-31 px-10" id="scroll-container">
                {children}
              </div>
      </body>
    </html>
  );
}
